{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.registrySecret.username }}
{{- $_ := set $registryAuthDocument "password" .Values.registrySecret.password }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $dockerAuthDocument := dict .Values.registrySecret.registryURL $registryAuthDocument }}
{{- $dockerConfigJSONDocument := dict "auths" $dockerAuthDocument -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  {{- if .Values.registrySecret.annotations }}
  namespace: {{ .Release.Namespace }}
  annotations: {{- toYaml .Values.registrySecret.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.registrySecret.labels }}
  labels: {{- toYaml .Values.registrySecret.labels | nindent 4 }}
  {{- end }}
data:
  .dockerconfigjson: {{ $dockerConfigJSONDocument | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson

---
apiVersion: ops.alexellis.io/v1
kind: ClusterPullSecret
metadata:
  name: docker-registry
spec:
  secretRef:
    name: {{ .Chart.Name }}-secret
    namespace: {{ .Release.Namespace }}
