replicaCount: 1

image:
  repository: ghcr.io/alexellis/registry-creds
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

container:
  args: ["--enable-leader-election"]
  command: ["/controller"]

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 45Mi

terminationGracePeriodSeconds: 10

nodeSelector: {}

tolerations: []

affinity: {}

registrySecret:
  username: username
  password: password
  registryURL: "https://index.docker.io/v1/"
